version: "3.9"

services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    restart: unless-stopped    

  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    restart: unless-stopped    
